doctrine_mongodb:
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options: {}
  default_database: '%env(resolve:MONGODB_DB)%'
  document_managers:
    default:
      auto_mapping: false
      mappings:
        App:
          is_bundle: false
          type: xml
          dir: '%kernel.project_dir%/config/doctrine'
          prefix: 'App\Document'
          alias: App