index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index
register:
    path: /signup
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# api
api_register:
    path: /api/register
    controller: App\Controller\UserController::registerByJson
    methods: POST