index:
    path: /
    methods: GET
    controller: App\Controller\GameController::menu
menu:
    path: /menu
    controller: App\Controller\GameController::menu
#регистрация логинация
register:
    path: /signup
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
#страницы меню
profile:
    path: /profile/{login}
    controller: App\Controller\PlayerController::profile
about:
    path: /about
    controller: App\Controller\GameController::about
statistics:
    path: /statistics/{login}
    controller: App\Controller\PlayerController::statistics
leaderboard:
    path: /leaderboard
    controller: App\Controller\GameController::leaderboard
settings:
    path: /settings
    controller: App\Controller\GameController::settings    
#мультиплеер
join:
    path: /join
    controller: App\Controller\GameController::join
lobby:
    path: /lobby
    controller: App\Controller\GameController::lobby
multiplayer:
    path: /multiplayer
    methods: GET
    controller: App\Controller\GameController::multiplayer
game_over_multi:
    path: /game_over_multi
    controller: App\Controller\GameController::gameOverMulti
#выбор режимов
select_multiplayer_mode:
    path: /select_multiplayer_mode
    controller: App\Controller\GameController::selectMultiplayerMode
select_classic_mode:
    path: /select_classic_mode
    controller: App\Controller\GameController::selectDif
select_koop_mode:
    path: /select_koop_mode
    controller: App\Controller\GameController::selectKoop
select_solo_mode:
    path: /select_solo_mode
    controller: App\Controller\GameController::selectSoloMode
#игра
game:
    path: /game
    controller: App\Controller\GameController::game
blitz:
    path: /blitz
    controller: App\Controller\GameController::blitz
bot:
    path: /bot
    controller: App\Controller\GameController::bot
koop:
    path: /koop
    controller: App\Controller\GameController::koop
l40:
    path: /l40
    controller: App\Controller\GameController::l40
game_over:
    path: /game_over
    controller: App\Controller\GameController::gameOver
game_over_mode:
    path: /game_over_mode
    controller: App\Controller\GameController::gameOverMode
download_image:
    path: /image
    methods: POST
    controller: App\Controller\PlayerController::updateAvatarPath
# api
api_register:
    path: /api/register
    controller: App\Controller\UserController::registerByJson
    methods: POST
api_save_single_game:
    path: /api/game/single/add
    methods: POST
    controller: App\Controller\PlayerController::storeSingleGame
api_save_multiplayer_game:
    path: /api/game/multiplayer/add
    methods: POST
    controller: App\Controller\GameController::storeMultiplayerGame
api_update_statistics:
    path: /api/statistics
    methods: POST
    controller: App\Controller\PlayerController::updateStatistics
api_get_players_rating:
    path: /api/player/rating
    methods: GET
    controller: App\Controller\PlayerController::getRating
api_get_user:
    path: /api/player/{id}
    methods: GET
    controller: App\Controller\PlayerController::getUserApi
api_get_game_rating:
    path: /api/game/rating
    methods: GET
    controller: App\Controller\GameController::getGamesWithFiltering
api_get_game_count:
    path: /api/game/count
    methods: GET
    controller: App\Controller\GameController::countGamesWithFiltering


test:
    path: /test
    controller: App\Controller\NoSQLTestController::get
