index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index
register:
    path: /signup
    controller: App\Controller\UserController::register
menu:
    path: /menu
    controller: App\Controller\UserController::menu
game_over:
    path: /game_over
    controller: App\Controller\UserController::game_over




# api
api_register:
    path: /api/register
    controller: App\Controller\UserController::registerByJson
    methods: POST