index:
    path: /
    methods: GET
    controller: App\Controller\GameController::menu
register:
    path: /signup
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

lobby:
    path: /lobby
    controller: App\Controller\GameController::lobby

menu:
    path: /menu
    controller: App\Controller\GameController::menu
select_mode:
    path: /select_mode
    controller: App\Controller\GameController::selectMode
select_classic_mode:
    path: /select_classic_mode
    controller: App\Controller\GameController::selectClassicMode
select_solo_mode:
    path: /select_solo_mode
    controller: App\Controller\GameController::selectSoloMode
about:
    path: /about
    controller: App\Controller\GameController::about
game_over:
    path: /game_over
    controller: App\Controller\GameController::gameOver
blitz_game_over:
    path: /blitz_game_over
    controller: App\Controller\GameController::blitzGameOver
game:
    path: /game
    controller: App\Controller\GameController::game
blitz:
    path: /blitz
    controller: App\Controller\GameController::blitz

profile:
    path: /profile/{login}
    controller: App\Controller\PlayerController::profile
multiplayer:
    path: /multiplayer
    methods: GET
    controller: App\Controller\GameController::multiplayer

get_user:
    path: /api/player/{id}/user
    methods: GET
    controller: App\Controller\PlayerController::getUserApi

# api
api_register:
    path: /api/register
    controller: App\Controller\UserController::registerByJson
    methods: POST
api_update_statistics:
    path: /api/statistics
    methods: POST
    controller: App\Controller\PlayerController::updateStatistics
