index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index
register:
    path: /signup
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

menu:
    path: /menu
    controller: App\Controller\GameController::menu
game_over:
    path: /game_over
    controller: App\Controller\GameController::game_over
game:
    path: /game
    controller: App\Controller\GameController::game
login-page:
    path: /login-page
    controller: App\Controller\GameController::loginPage

# api
api_register:
    path: /api/register
    controller: App\Controller\UserController::registerByJson
    methods: POST