index:
    path: /
    methods: GET
    controller: App\Controller\GameController::menu
register:
    path: /signup
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

lobby:
    path: /lobby
    controller: App\Controller\GameController::lobby
join:
    path: /join
    controller: App\Controller\GameController::join
menu:
    path: /menu
    controller: App\Controller\GameController::menu
select_multiplayer_mode:
    path: /select_multiplayer_mode
    controller: App\Controller\GameController::selectMultiplayerMode
select_classic_mode:
    path: /select_classic_mode
    controller: App\Controller\GameController::selectDif
select_koop_mode:
    path: /select_koop_mode
    controller: App\Controller\GameController::selectKoop
select_solo_mode:
    path: /select_solo_mode
    controller: App\Controller\GameController::selectSoloMode
about:
    path: /about
    controller: App\Controller\GameController::about
game_over:
    path: /game_over
    controller: App\Controller\GameController::gameOver
game_over_multi:
    path: /game_over_multi
    controller: App\Controller\GameController::gameOverMulti
game:
    path: /game
    controller: App\Controller\GameController::game
blitz:
    path: /blitz
    controller: App\Controller\GameController::blitz
koop:
    path: /koop
    controller: App\Controller\GameController::koop
l40:
    path: /l40
    controller: App\Controller\GameController::l40
profile:
    path: /profile/{login}
    controller: App\Controller\PlayerController::profile
multiplayer:
    path: /multiplayer
    methods: GET
    controller: App\Controller\GameController::multiplayer

get_user:
    path: /api/player/{id}/user
    methods: GET
    controller: App\Controller\PlayerController::getUserApi

# api
api_register:
    path: /api/register
    controller: App\Controller\UserController::registerByJson
    methods: POST
api_update_statistics:
    path: /api/statistics
    methods: POST
    controller: App\Controller\PlayerController::updateStatistics


nosql_test_create:
    path: /create
    controller: App\Controller\NoSQLTestController::create

nosql_test_get:
    path: /get
    controller: App\Controller\NoSQLTestController::get
