index:
    path: /
    methods: GET
    controller: App\Controller\GameController::menu
register:
    path: /signup
    controller: App\Controller\UserController::register
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

menu:
    path: /menu
    controller: App\Controller\GameController::menu
game_over:
    path: /game_over
    controller: App\Controller\GameController::gameOver
game:
    path: /game
    controller: App\Controller\GameController::game


# api
api_register:
    path: /api/register
    controller: App\Controller\UserController::registerByJson
    methods: POST
api_update_statistics:
    path: /api/statistics
    methods: POST
    controller: App\Controller\PlayerController::updateStatistics